name: Build and Test and Deploy
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  npm_security_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Security Tests
        run: npm run npm-test-security

  user_inteface_tests:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Playwright
        run: npx playwright install
      - name: Install Playwright Dependencies
        run: npm install @playwright/test@latest
      - name: Install Dependencies
        run: npm install
      - name: Run User interface Tests
        run: npm run test:ui
  softuni_username:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Chech SoftUni username
        run: echo "SoftUni Username - jvalkov"

  deploy_to_render:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Deploy to Render in Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_WEB_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
